#spring.application.name=g_44_Shop
#spring.datasource.url=jdbc:postgresql://localhost:5432/g_44_shop
#spring.datasource.username=postgres
#spring.datasource.password=pos1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}/g_44_shop
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

server:
  servlet:
    context-path: /api

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

#
#